#将该文件放置在tiktak/config文件夹下即可正常使用
#注意不要将该文件push到仓库上去

server:
  port: :8081
datasource:
  #mysql配置
  mysql:
    host: 127.0.0.1
    port: 3306
    database: douyin
    username: root
    password: 1234
    charset: utf8
    maxIdle: 50
    maxOpen: 70
    maxLifetime: 60*5
  #阿里云oss配置
  OSS:
    OSSBucket: tiktak
    OSSEndpoint: oss-cn-beijing.aliyuncs.com
    #oss 访问key
    OSSAccesskeyID: LTAI5tAZKdZkb3pvKemRDKhx
    #oss key密钥
    OSSAccesskeySecret: sb6YdY8qZjMiu9WJwEtBuNFfAlx5qV
  #redis配置 暂未兼容
  redis:
    addr: 
    db: 0
    password: Xt2DCWsbsAzdhmZE
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    max-idle: 200
    max-active: 2000
    max-wait: 1000
#token
secretkey: 6824douyin